title: "the nuptials"
description: "Wedding celebration details"
baseurl: "/chamelia-wedding"
url: ""

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
